### ISSUE TITLE
Cope

### ISSUE THREAD

**Issue by CheFuls** [AntiCope/meteor-rejects#53] opened 2021-09-06 13:04 UTC
### Describe the bug

Fix auto tnt

### Steps to reproduce

```bash
Bruuuuuuuuuhhhhh
```

### Operating System

Windows

### Meteor Version

0.4.5

### Minecraft Version

1.17

### Other mods

```bash
Meteor xd
```

**Comment by StormyBytes** [comment] 2021-09-06 13:21
Duplicate of #37

**Closed** 2021-09-06 13:21 UTC
Labels: bug, duplicate

**Comment by C10udburst** [comment] 2021-09-06 14:00
> Steps to reproduce
> Bruuuuuuuuuhhhhh

mfw
