### ISSUE TITLE
Game crashes when I try to open game 

### ISSUE THREAD

**Issue by 60YzArC** [AntiCope/meteor-rejects#140] opened 2022-07-23 21:50 UTC
### Describe the bug

Its outdated so yh.

### Crashlog

its outdated

### Steps to reproduce

1.open mc 
2.it crashes
3. cry
...

### Addon Version

Latest version

### Meteor Version

Latest version

### Minecraft Version

Latest version

### Other mods

```plaintext
1.I tried it with none 
2.
3.
...
```

**Comment by C10udburst** [comment] 2022-07-24 07:06
yeah, duplicate of #139

**Closed** 2022-07-24 07:06 UTC
Labels: bug
