### ISSUE TITLE
Adding compatiblity with 1.20.1 version as soon as possible please.

### ISSUE THREAD

**Issue by Python9874** [AntiCope/meteor-rejects#279] opened 2023-07-23 01:13 UTC
### Describe the feature

Everyone wants meteor client addons to support 1.20.1. Would you mind updating it to 1.20.1 the jar file so if i'm on Meteor version 1.20.1 it is compatible with fabric. Thanks alot: Seb!

**Comment by ManInMyVan** [comment] 2023-07-27 08:07
It already works on 1.20.1

**Comment by ManInMyVan** [comment] 2023-07-27 08:08
Also duplicate of #257

**Comment by ManInMyVan** [comment] 2023-08-12 05:34
Close, it exists

**Closed** 2023-08-12 07:52 UTC
Labels: enhancement
